package com.clc.backend.generator;

import static com.clc.backend.analizadores.sintactico.Sym.*;

/**
 *
 * @author vicente
 */
public class NameTokenGenerator {

    public static String getName(int idToken) {
        return
        switch (idToken) {
            case AQUA -> "aqua";
            case LEFT -> "left";
            case TIMES -> "signo de multipliacacion";
            case LESS_THAN -> "menor que";
            case COLUMN -> "column";
            case C_P -> "etqiueta C_P";
            case TYPE -> "type";
            case MARRON -> "marron";
            case GREATER_THAN -> "mayor que";
            case TEAL -> "teal";
            case RIGHT -> "right";
            case ROWS -> "rows";
            case SEMI -> "punto y coma";
            case ASC -> "asc";
            case CHECKBOX -> "checkbox";
            case NAME -> "name";
            case CLOSE_BRACKET -> "corchete cerrado";
            case ROW -> "row";
            case SANS_SERIF -> "sans-serif";
            case INIT -> "INIT";
            case C_CC -> "etqiueta CC";
            case COMMA -> "coma";
            case BLUE -> "blue";
            case ALT -> "alt";
            case YELLOW -> "yellow";
            case ENTERO2 -> "entero positivo o negativo";
            case FUCHSIA -> "fuchsia";
            case TEXT_ALIGN -> "text-align";
            case PROCESS_NAME -> "nombre de proceso";
            case LETIMPAR_NUM -> "funcion LETIMPAR_NUM";
            case DATOSCRIPT -> "id de etiqueta";
            case INTEGER -> "tipo dato integer";
            case BLACK -> "black";
            case NAME_PARAM -> "palabra alfanumerica";
            case C_LINK -> "etqiueta LINK";
            case GRAY -> "gray";
            case C_OPTION -> "etqiueta OPTION";
            case LITERAL -> "texto entre comillas dobles";
            case FALSE -> "false";
            case NOT -> "not";
            case BACKGROUND -> "background";
            case CENTER -> "center";
            case GREATER_THAN_OR_EQUAL_TO -> "mayor o igual que";
            case TEXT -> "text";
            case THENWHILE -> "THENWHILE";
            case C_SPAM -> "etqiueta SPAM";
            case THEN -> "THEN";
            case ID_VAR -> "identificador";
            case C_BODY -> "etqiueta BODY";
            case PURPLE -> "purple";
            case WIDTH -> "width";
            case CLOSE_BRACE -> "llave cerrada";
            case REVERSE -> "funcion REVERSE";
            case C_TEXTAREA -> "etqiueta TEXTAREA";
            case OPEN_BRACKET -> "corchete abierto";
            case CLASS -> "class";
            case ALERT_INFO -> "funcion ALERT_INFO";
            case C_DIV -> "etqiueta DIV";
            case NUMBER -> "number";
            case C_HEAD -> "etqiueta HEAD";
            case REDIRECT -> "funcion RERDIRECT";
            case NUM_ALEATORIO -> "funcion NUM_ALEATORIO";
            case ENTERO -> "entero";
            case HUNTIL -> "HUNTIL";
            case C_SCRIPTING -> "etqiueta SCRIPTING";
            case SLASH -> "diagonal";
            case OPEN_ROUND_BRACKET -> "parentesis abierto";
            case C_INPUT -> "etqiueta INPUT";
            case TRUE -> "true";
            case LESS_THAN_OR_EQUAL_TO -> "menor o igual que";
            case PLUS -> "operador suma";
            case DIVIDE -> "operador divicion";
            case OLIVE -> "olive";
            case WHILE -> "WHILE";
            case COLS -> "cols";
            case ASSIGN -> "signo igual";
            case CHAR -> "tipo dato char";
            case DECIMAL -> "tipo dato decimal";
            case BOOLEAN -> "tipo dato boolean";
            case JUSTIFY -> "justify";
            case GLOBAL_MODE -> "modo global";
            case NAVY -> "navy";
            case ELSE -> "ELSE";
            case COURIER -> "courier";
            case URL -> "direccion url";
            case C_BR -> "etqiueta BR";
            case EOF -> "fin de linea";
            case ARIAL -> "arial";
            case C_TITLE -> "etqiueta TITLE";
            case REPEAT -> "REPEAT";
            case C_IMG -> "etqiueta IMG";
            case NOT_EQTUAL_TO -> "operador diferente de";
            case MINUS -> "operador resta";
            case VERDANA -> "verdana";
            case QOUTE_MARK -> "comillas dobles";
            case GENEVA -> "geneva";
            case DECIMAL_VAL -> "valor decimal";
            case SRC -> "SRC";
            case EQUAL_TO -> "operador igual a";
            case HREF -> "HREF";
            case OR -> "operador or";
            case EXIT -> "funcion EXIT";
            case error -> "error";
            case TEXT_TAG -> "texto entre etiquetas";
            case IF -> "IF";
            case DESC -> "funcion DESC";
            case ID -> "id";
            case COLOR -> "color";
            case ON_LOAD -> "proceso ON_LOAD";
            case C_SELECT -> "etqiueta select";
            case COLOR_VALUE -> "color value";
            case END -> "END";
            case WH_VAL -> "tamaño en pixeles";
            case COLON -> "dos puntos";
            case SILVER -> "silver";
            case C_H1 -> "etqiueta H1";
            case LIME -> "lime";
            case RADIO -> "radio";
            case HEIGHT -> "height";
            case OPEN_BRACE -> "llave abierta";
            case RED -> "red";
            case ID_PARAM -> "identificador etiqueta";
            case CARACTER_ALEATORIO -> "funcion CARACTER_ALEATORIO";
            case FONT_FAMILY -> "font-family";
            case CLOSE_ROUND_BRACKET -> "parentesis cerrado";
            case FONT_SIZE -> "font-size";
            case INSERT -> "INSERT";
            case CHAR_VAL -> "char value";
            case STRING -> "tipo dato string";
            case SIZE -> "size";
            case ONCLICK -> "onclick";
            case AND -> "AND";
            case C_BUTTON -> "etqiueta button";
            case LETPAR_NUM -> "funcion LETPAR_NUM";
            case ELEMENT_BY_ID -> "funcion elementById";
            case GREEN -> "green";
            default -> "";
        };
    }
}
