
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.clc.backend.analizadores.sintactico;

/** CUP generated class containing symbol constants. */
public class StorageSym {
  /* terminals */
  public static final int CLOSE_BRACKET = 7;
  public static final int OPEN_BRACE = 4;
  public static final int VALUE = 17;
  public static final int NAME = 10;
  public static final int LITERAL = 18;
  public static final int COLON = 2;
  public static final int ID = 9;
  public static final int OPEN_BRACKET = 6;
  public static final int COMMA = 3;
  public static final int EOF = 0;
  public static final int FAULTS = 13;
  public static final int LAST_DATE = 14;
  public static final int FECHA = 15;
  public static final int CLOSE_BRACE = 5;
  public static final int error = 1;
  public static final int USE = 11;
  public static final int ENTERO = 16;
  public static final int CAPTCHAS = 8;
  public static final int HITS = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COLON",
  "COMMA",
  "OPEN_BRACE",
  "CLOSE_BRACE",
  "OPEN_BRACKET",
  "CLOSE_BRACKET",
  "CAPTCHAS",
  "ID",
  "NAME",
  "USE",
  "HITS",
  "FAULTS",
  "LAST_DATE",
  "FECHA",
  "ENTERO",
  "VALUE",
  "LITERAL"
  };
}

